#!/bin/bash

# Must have environment variables set for MYSQL connection in ufront-orm tests.
# eg. MYSQL_HOST="localhost" MYSQL_PORT="3306" MYSQL_USER="ufrontormtest" MYSQL_PASSWORD="ufrontormtest" MYSQL_DATABASE="ufrontormtest"  ./runtests

function stop {
	PROGNAME=$(basename $0)
	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
	exit 1
}

# Compile our docs.
haxe doc.hxml || stop "Failed to compile API documentation"
rm -Rf doc/api/*
mkdir -p doc/api/
cd doc/
haxelib install dox
haxelib run dox -i . -o api/ --title "Ufront-API-Docs" -in . -ex Test$ -t ufront-api/templates/ -res ufront-api/resources/ || stop "Failed to proces API docs"
cd ../

# Ufront-mvc tests.
cd submodules/ufront-mvc/
haxe test.hxml || stop "Failed to compile ufront-mvc tests"
neko build/neko_test.n || stop "ufront-mvc tests failed on Neko"
php build/php_test.php || stop "ufront-mvc tests failed on PHP"
cd ../../

# Ufront-orm tests.
cd submodules/ufront-orm
#./testAll.sh || stop "ufront-orm tests failed"
cd ../../

# Compile ufront-hello
cd submodules/hello
ufront b || stop "Failed to compile hello world example"
cd ../../
