#!/bin/sh

haxelib dev ufront .
haxelib dev hxnodejs submodules/hxnodejs
haxelib dev express submodules/hxexpress
haxelib dev minject submodules/minject
haxelib dev ufront-client submodules/ufront-client
haxelib dev ufront-easyauth submodules/ufront-easyauth
haxelib dev ufront-mail submodules/ufront-mail
haxelib dev ufront-mvc submodules/ufront-mvc
haxelib dev ufront-orm submodules/ufront-orm
haxelib dev ufront-ufadmin submodules/ufront-ufadmin
haxelib dev ufront-uftasks submodules/ufront-uftasks
