#!/bin/sh

set -x #echo on

haxelib dev ufront .
haxelib dev ufront-client submodules/ufront-client
haxelib dev ufront-easyauth submodules/ufront-easyauth
haxelib dev ufront-mail submodules/ufront-mail
haxelib dev ufront-mvc submodules/ufront-mvc
haxelib dev ufront-orm submodules/ufront-orm
haxelib dev ufront-ufadmin submodules/ufront-ufadmin
haxelib dev ufront-uftasks submodules/ufront-uftasks
# Reset things that no longer need to be dev versions.
haxelib dev minject
haxelib set minject 2.0.0-rc.1
haxelib dev hxnodejs
haxelib set hxnodejs 4.0.4
haxelib dev express
haxelib set express 0.3.1
