package thx.color;

/**
 * ...
 * @author Franco Ponticelli
 */

class NamedColors
{
	public static var aliceblue(default, null) : Rgb;
	public static var antiquewhite(default, null) : Rgb;
	public static var aqua(default, null) : Rgb;
	public static var aquamarine(default, null) : Rgb;
	public static var azure(default, null) : Rgb;
	public static var beige(default, null) : Rgb;
	public static var bisque(default, null) : Rgb;
	public static var black(default, null) : Rgb;
	public static var blanchedalmond(default, null) : Rgb;
	public static var blue(default, null) : Rgb;
	public static var blueviolet(default, null) : Rgb;
	public static var brown(default, null) : Rgb;
	public static var burlywood(default, null) : Rgb;
	public static var cadetblue(default, null) : Rgb;
	public static var chartreuse(default, null) : Rgb;
	public static var chocolate(default, null) : Rgb;
	public static var coral(default, null) : Rgb;
	public static var cornflowerblue(default, null) : Rgb;
	public static var cornsilk(default, null) : Rgb;
	public static var crimson(default, null) : Rgb;
	public static var cyan(default, null) : Rgb;
	public static var darkblue(default, null) : Rgb;
	public static var darkcyan(default, null) : Rgb;
	public static var darkgoldenrod(default, null) : Rgb;
	public static var darkgray(default, null) : Rgb;
	public static var darkgreen(default, null) : Rgb;
	public static var darkgrey(default, null) : Rgb;
	public static var darkkhaki(default, null) : Rgb;
	public static var darkmagenta(default, null) : Rgb;
	public static var darkolivegreen(default, null) : Rgb;
	public static var darkorange(default, null) : Rgb;
	public static var darkorchid(default, null) : Rgb;
	public static var darkred(default, null) : Rgb;
	public static var darksalmon(default, null) : Rgb;
	public static var darkseagreen(default, null) : Rgb;
	public static var darkslateblue(default, null) : Rgb;
	public static var darkslategray(default, null) : Rgb;
	public static var darkslategrey(default, null) : Rgb;
	public static var darkturquoise(default, null) : Rgb;
	public static var darkviolet(default, null) : Rgb;
	public static var deeppink(default, null) : Rgb;
	public static var deepskyblue(default, null) : Rgb;
	public static var dimgray(default, null) : Rgb;
	public static var dimgrey(default, null) : Rgb;
	public static var dodgerblue(default, null) : Rgb;
	public static var firebrick(default, null) : Rgb;
	public static var floralwhite(default, null) : Rgb;
	public static var forestgreen(default, null) : Rgb;
	public static var fuchsia(default, null) : Rgb;
	public static var gainsboro(default, null) : Rgb;
	public static var ghostwhite(default, null) : Rgb;
	public static var gold(default, null) : Rgb;
	public static var goldenrod(default, null) : Rgb;
	public static var gray(default, null) : Rgb;
	public static var green(default, null) : Rgb;
	public static var greenyellow(default, null) : Rgb;
	public static var grey(default, null) : Rgb;
	public static var honeydew(default, null) : Rgb;
	public static var hotpink(default, null) : Rgb;
	public static var indianred(default, null) : Rgb;
	public static var indigo(default, null) : Rgb;
	public static var ivory(default, null) : Rgb;
	public static var khaki(default, null) : Rgb;
	public static var lavender(default, null) : Rgb;
	public static var lavenderblush(default, null) : Rgb;
	public static var lawngreen(default, null) : Rgb;
	public static var lemonchiffon(default, null) : Rgb;
	public static var lightblue(default, null) : Rgb;
	public static var lightcoral(default, null) : Rgb;
	public static var lightcyan(default, null) : Rgb;
	public static var lightgoldenrodyellow(default, null) : Rgb;
	public static var lightgray(default, null) : Rgb;
	public static var lightgreen(default, null) : Rgb;
	public static var lightgrey(default, null) : Rgb;
	public static var lightpink(default, null) : Rgb;
	public static var lightsalmon(default, null) : Rgb;
	public static var lightseagreen(default, null) : Rgb;
	public static var lightskyblue(default, null) : Rgb;
	public static var lightslategray(default, null) : Rgb;
	public static var lightslategrey(default, null) : Rgb;
	public static var lightsteelblue(default, null) : Rgb;
	public static var lightyellow(default, null) : Rgb;
	public static var lime(default, null) : Rgb;
	public static var limegreen(default, null) : Rgb;
	public static var linen(default, null) : Rgb;
	public static var magenta(default, null) : Rgb;
	public static var maroon(default, null) : Rgb;
	public static var mediumaquamarine(default, null) : Rgb;
	public static var mediumblue(default, null) : Rgb;
	public static var mediumorchid(default, null) : Rgb;
	public static var mediumpurple(default, null) : Rgb;
	public static var mediumseagreen(default, null) : Rgb;
	public static var mediumslateblue(default, null) : Rgb;
	public static var mediumspringgreen(default, null) : Rgb;
	public static var mediumturquoise(default, null) : Rgb;
	public static var mediumvioletred(default, null) : Rgb;
	public static var midnightblue(default, null) : Rgb;
	public static var mintcream(default, null) : Rgb;
	public static var mistyrose(default, null) : Rgb;
	public static var moccasin(default, null) : Rgb;
	public static var navajowhite(default, null) : Rgb;
	public static var navy(default, null) : Rgb;
	public static var oldlace(default, null) : Rgb;
	public static var olive(default, null) : Rgb;
	public static var olivedrab(default, null) : Rgb;
	public static var orange(default, null) : Rgb;
	public static var orangered(default, null) : Rgb;
	public static var orchid(default, null) : Rgb;
	public static var palegoldenrod(default, null) : Rgb;
	public static var palegreen(default, null) : Rgb;
	public static var paleturquoise(default, null) : Rgb;
	public static var palevioletred(default, null) : Rgb;
	public static var papayawhip(default, null) : Rgb;
	public static var peachpuff(default, null) : Rgb;
	public static var peru(default, null) : Rgb;
	public static var pink(default, null) : Rgb;
	public static var plum(default, null) : Rgb;
	public static var powderblue(default, null) : Rgb;
	public static var purple(default, null) : Rgb;
	public static var red(default, null) : Rgb;
	public static var rosybrown(default, null) : Rgb;
	public static var royalblue(default, null) : Rgb;
	public static var saddlebrown(default, null) : Rgb;
	public static var salmon(default, null) : Rgb;
	public static var sandybrown(default, null) : Rgb;
	public static var seagreen(default, null) : Rgb;
	public static var seashell(default, null) : Rgb;
	public static var sienna(default, null) : Rgb;
	public static var silver(default, null) : Rgb;
	public static var skyblue(default, null) : Rgb;
	public static var slateblue(default, null) : Rgb;
	public static var slategray(default, null) : Rgb;
	public static var slategrey(default, null) : Rgb;
	public static var snow(default, null) : Rgb;
	public static var springgreen(default, null) : Rgb;
	public static var steelblue(default, null) : Rgb;
	public static var tan(default, null) : Rgb;
	public static var teal(default, null) : Rgb;
	public static var thistle(default, null) : Rgb;
	public static var tomato(default, null) : Rgb;
	public static var turquoise(default, null) : Rgb;
	public static var violet(default, null) : Rgb;
	public static var wheat(default, null) : Rgb;
	public static var white(default, null) : Rgb;
	public static var whitesmoke(default, null) : Rgb;
	public static var yellow(default, null) : Rgb;
	public static var yellowgreen(default, null) : Rgb;
	public static var byName(default, null) : Map<String, Rgb>;

	static function __init__()
	{
		byName = new Map ();
		byName.set("aliceblue", aliceblue = Rgb.fromInt(0xf0f8ff));
		byName.set("alice blue", aliceblue);
		byName.set("antiquewhite", antiquewhite = Rgb.fromInt(0xfaebd7));
		byName.set("antique white", antiquewhite);
		byName.set("aqua", aqua = Rgb.fromInt(0x00ffff));
		byName.set("aquamarine", aquamarine = Rgb.fromInt(0x7fffd4));
		byName.set("azure", azure = Rgb.fromInt(0xf0ffff));
		byName.set("beige", beige = Rgb.fromInt(0xf5f5dc));
		byName.set("bisque", bisque = Rgb.fromInt(0xffe4c4));
		byName.set("black", black = Rgb.fromInt(0x000000));
		byName.set("blanchedalmond", blanchedalmond = Rgb.fromInt(0xffebcd));
		byName.set("blanched almond", blanchedalmond);
		byName.set("blue", blue = Rgb.fromInt(0x0000ff));
		byName.set("blueviolet", blueviolet = Rgb.fromInt(0x8a2be2));
		byName.set("blue violet", blueviolet);
		byName.set("brown", brown = Rgb.fromInt(0xa52a2a));
		byName.set("burlywood", burlywood = Rgb.fromInt(0xdeb887));
		byName.set("burly wood", burlywood);
		byName.set("cadetblue", cadetblue = Rgb.fromInt(0x5f9ea0));
		byName.set("cadet blue", cadetblue);
		byName.set("chartreuse", chartreuse = Rgb.fromInt(0x7fff00));
		byName.set("chart reuse", chartreuse);
		byName.set("chocolate", chocolate = Rgb.fromInt(0xd2691e));
		byName.set("coral", coral = Rgb.fromInt(0xff7f50));
		byName.set("cornflowerblue", cornflowerblue = Rgb.fromInt(0x6495ed));
		byName.set("corn flower blue", cornflowerblue);
		byName.set("cornsilk", cornsilk = Rgb.fromInt(0xfff8dc));
		byName.set("corn silk", cornsilk);
		byName.set("crimson", crimson = Rgb.fromInt(0xdc143c));
		byName.set("cyan", cyan = Rgb.fromInt(0x00ffff));
		byName.set("darkblue", darkblue = Rgb.fromInt(0x00008b));
		byName.set("dark blue", darkblue);
		byName.set("darkcyan", darkcyan = Rgb.fromInt(0x008b8b));
		byName.set("dark cyan", darkcyan);
		byName.set("darkgoldenrod", darkgoldenrod = Rgb.fromInt(0xb8860b));
		byName.set("dark golden rod", darkgoldenrod);
		byName.set("darkgray", darkgray = darkgrey = Rgb.fromInt(0xa9a9a9));
		byName.set("dark gray", darkgray);
		byName.set("darkgrey", darkgrey);
		byName.set("dark grey", darkgrey);
		byName.set("darkgreen", darkgreen = Rgb.fromInt(0x006400));
		byName.set("dark green", darkgreen);
		byName.set("darkkhaki", darkkhaki = Rgb.fromInt(0xbdb76b));
		byName.set("dark khaki", darkkhaki);
		byName.set("darkmagenta", darkmagenta = Rgb.fromInt(0x8b008b));
		byName.set("dark magenta", darkmagenta);
		byName.set("darkolivegreen", darkolivegreen = Rgb.fromInt(0x556b2f));
		byName.set("dark olive green", darkolivegreen);
		byName.set("darkorange", darkorange = Rgb.fromInt(0xff8c00));
		byName.set("dark orange", darkorange);
		byName.set("darkorchid", darkorchid = Rgb.fromInt(0x9932cc));
		byName.set("dark orchid", darkorchid);
		byName.set("darkred", darkred = Rgb.fromInt(0x8b0000));
		byName.set("dark red", darkred);
		byName.set("darksalmon", darksalmon = Rgb.fromInt(0xe9967a));
		byName.set("dark salmon", darksalmon);
		byName.set("darkseagreen", darkseagreen = Rgb.fromInt(0x8fbc8f));
		byName.set("dark sea green", darkseagreen);
		byName.set("darkslateblue", darkslateblue = Rgb.fromInt(0x483d8b));
		byName.set("dark slate blue", darkslateblue);
		byName.set("darkslategray", darkslategray = darkslategrey = Rgb.fromInt(0x2f4f4f));
		byName.set("dark slate gray", darkslategray);
		byName.set("darkslategrey", darkslategrey);
		byName.set("dark slate grey", darkslategrey);
		byName.set("darkturquoise", darkturquoise = Rgb.fromInt(0x00ced1));
		byName.set("dark turquoise", darkturquoise);
		byName.set("darkviolet", darkviolet = Rgb.fromInt(0x9400d3));
		byName.set("dark violet", darkviolet);
		byName.set("deeppink", deeppink = Rgb.fromInt(0xff1493));
		byName.set("deep pink", deeppink);
		byName.set("deepskyblue", deepskyblue = Rgb.fromInt(0x00bfff));
		byName.set("deep sky blue", deepskyblue);
		byName.set("dimgray", dimgray = dimgrey = Rgb.fromInt(0x696969));
		byName.set("dim grey", dimgrey);
		byName.set("dimgrey", dimgrey);
		byName.set("dim grey", dimgrey);
		byName.set("dodgerblue", dodgerblue = Rgb.fromInt(0x1e90ff));
		byName.set("dodger blue", dodgerblue);
		byName.set("firebrick", firebrick = Rgb.fromInt(0xb22222));
		byName.set("fire brick", firebrick);
		byName.set("floralwhite", floralwhite = Rgb.fromInt(0xfffaf0));
		byName.set("floral white", floralwhite);
		byName.set("forestgreen", forestgreen = Rgb.fromInt(0x228b22));
		byName.set("forest green", forestgreen);
		byName.set("fuchsia", fuchsia = Rgb.fromInt(0xff00ff));
		byName.set("gainsboro", gainsboro = Rgb.fromInt(0xdcdcdc));
		byName.set("ghostwhite", ghostwhite = Rgb.fromInt(0xf8f8ff));
		byName.set("ghost white", ghostwhite);
		byName.set("gold", gold = Rgb.fromInt(0xffd700));
		byName.set("goldenrod", goldenrod = Rgb.fromInt(0xdaa520));
		byName.set("golden rod", goldenrod);
		byName.set("gray", gray = grey = Rgb.fromInt(0x808080));
		byName.set("grey", grey);
		byName.set("green", green = Rgb.fromInt(0x008000));
		byName.set("greenyellow", greenyellow = Rgb.fromInt(0xadff2f));
		byName.set("green yellow", greenyellow);
		byName.set("honeydew", honeydew = Rgb.fromInt(0xf0fff0));
		byName.set("honey dew", honeydew);
		byName.set("hotpink", hotpink = Rgb.fromInt(0xff69b4));
		byName.set("hot pink", hotpink);
		byName.set("indianred", indianred = Rgb.fromInt(0xcd5c5c));
		byName.set("indian red", indianred);
		byName.set("indigo", indigo = Rgb.fromInt(0x4b0082));
		byName.set("ivory", ivory = Rgb.fromInt(0xfffff0));
		byName.set("khaki", khaki = Rgb.fromInt(0xf0e68c));
		byName.set("lavender", lavender = Rgb.fromInt(0xe6e6fa));
		byName.set("lavenderblush", lavenderblush = Rgb.fromInt(0xfff0f5));
		byName.set("lavender blush", lavenderblush);
		byName.set("lawngreen", lawngreen = Rgb.fromInt(0x7cfc00));
		byName.set("lawn green", lawngreen);
		byName.set("lemonchiffon", lemonchiffon = Rgb.fromInt(0xfffacd));
		byName.set("lemon chiffon", lemonchiffon);
		byName.set("lightblue", lightblue = Rgb.fromInt(0xadd8e6));
		byName.set("light blue", lightblue);
		byName.set("lightcoral", lightcoral = Rgb.fromInt(0xf08080));
		byName.set("light coral", lightcoral);
		byName.set("lightcyan", lightcyan = Rgb.fromInt(0xe0ffff));
		byName.set("light cyan", lightcyan);
		byName.set("lightgoldenrodyellow", lightgoldenrodyellow = Rgb.fromInt(0xfafad2));
		byName.set("light golden rod yellow", lightgoldenrodyellow);
		byName.set("lightgray", lightgray = lightgrey = Rgb.fromInt(0xd3d3d3));
		byName.set("light gray", lightgray);
		byName.set("lightgrey", lightgrey);
		byName.set("light grey", lightgrey);
		byName.set("lightgreen", lightgreen = Rgb.fromInt(0x90ee90));
		byName.set("light green", lightgreen);
		byName.set("lightpink", lightpink = Rgb.fromInt(0xffb6c1));
		byName.set("light pink", lightpink);
		byName.set("lightsalmon", lightsalmon = Rgb.fromInt(0xffa07a));
		byName.set("light salmon", lightsalmon);
		byName.set("lightseagreen", lightseagreen = Rgb.fromInt(0x20b2aa));
		byName.set("light sea green", lightseagreen);
		byName.set("lightskyblue", lightskyblue = Rgb.fromInt(0x87cefa));
		byName.set("light sky blue", lightskyblue);
		byName.set("lightslategray", lightslategray = lightslategrey = Rgb.fromInt(0x778899));
		byName.set("light slate gray", lightslategray);
		byName.set("lightslategrey", lightslategrey);
		byName.set("light slate grey", lightslategrey);
		byName.set("lightsteelblue", lightsteelblue = Rgb.fromInt(0xb0c4de));
		byName.set("light steel blue", lightsteelblue);
		byName.set("lightyellow", lightyellow = Rgb.fromInt(0xffffe0));
		byName.set("light yellow", lightyellow);
		byName.set("lime", lime = Rgb.fromInt(0x00ff00));
		byName.set("limegreen", limegreen = Rgb.fromInt(0x32cd32));
		byName.set("lime green", limegreen);
		byName.set("linen", linen = Rgb.fromInt(0xfaf0e6));
		byName.set("magenta", magenta = Rgb.fromInt(0xff00ff));
		byName.set("maroon", maroon = Rgb.fromInt(0x800000));
		byName.set("mediumaquamarine", mediumaquamarine = Rgb.fromInt(0x66cdaa));
		byName.set("mediuma quamarine", mediumaquamarine);
		byName.set("mediumblue", mediumblue = Rgb.fromInt(0x0000cd));
		byName.set("medium blue", mediumblue);
		byName.set("mediumorchid", mediumorchid = Rgb.fromInt(0xba55d3));
		byName.set("medium orchid", mediumorchid);
		byName.set("mediumpurple", mediumpurple = Rgb.fromInt(0x9370db));
		byName.set("medium purple", mediumpurple);
		byName.set("mediumseagreen", mediumseagreen = Rgb.fromInt(0x3cb371));
		byName.set("medium sea green", mediumseagreen);
		byName.set("mediumslateblue", mediumslateblue = Rgb.fromInt(0x7b68ee));
		byName.set("medium slate blue", mediumslateblue);
		byName.set("mediumspringgreen", mediumspringgreen = Rgb.fromInt(0x00fa9a));
		byName.set("medium spring green", mediumspringgreen);
		byName.set("mediumturquoise", mediumturquoise = Rgb.fromInt(0x48d1cc));
		byName.set("medium turquoise", mediumturquoise);
		byName.set("mediumvioletred", mediumvioletred = Rgb.fromInt(0xc71585));
		byName.set("medium violet red", mediumvioletred);
		byName.set("midnightblue", midnightblue = Rgb.fromInt(0x191970));
		byName.set("midnight blue", midnightblue);
		byName.set("mintcream", mintcream = Rgb.fromInt(0xf5fffa));
		byName.set("mint cream", mintcream);
		byName.set("mistyrose", mistyrose = Rgb.fromInt(0xffe4e1));
		byName.set("misty rose", mistyrose);
		byName.set("moccasin", moccasin = Rgb.fromInt(0xffe4b5));
		byName.set("navajowhite", navajowhite = Rgb.fromInt(0xffdead));
		byName.set("navajo white", navajowhite);
		byName.set("navy", navy = Rgb.fromInt(0x000080));
		byName.set("oldlace", oldlace = Rgb.fromInt(0xfdf5e6));
		byName.set("old lace", oldlace);
		byName.set("olive", olive = Rgb.fromInt(0x808000));
		byName.set("olivedrab", olivedrab = Rgb.fromInt(0x6b8e23));
		byName.set("olive drab", olivedrab);
		byName.set("orange", orange = Rgb.fromInt(0xffa500));
		byName.set("orangered", orangered = Rgb.fromInt(0xff4500));
		byName.set("orangered", orangered);
		byName.set("orchid", orchid = Rgb.fromInt(0xda70d6));
		byName.set("palegoldenrod", palegoldenrod = Rgb.fromInt(0xeee8aa));
		byName.set("pale golden rod", palegoldenrod);
		byName.set("palegreen", palegreen = Rgb.fromInt(0x98fb98));
		byName.set("pale green", palegreen);
		byName.set("paleturquoise", paleturquoise = Rgb.fromInt(0xafeeee));
		byName.set("pale turquoise", paleturquoise);
		byName.set("palevioletred", palevioletred = Rgb.fromInt(0xdb7093));
		byName.set("pale violet red", palevioletred);
		byName.set("papayawhip", papayawhip = Rgb.fromInt(0xffefd5));
		byName.set("papaya whip", papayawhip);
		byName.set("peachpuff", peachpuff = Rgb.fromInt(0xffdab9));
		byName.set("peach puff", peachpuff);
		byName.set("peru", peru = Rgb.fromInt(0xcd853f));
		byName.set("pink", pink = Rgb.fromInt(0xffc0cb));
		byName.set("plum", plum = Rgb.fromInt(0xdda0dd));
		byName.set("powderblue", powderblue = Rgb.fromInt(0xb0e0e6));
		byName.set("powder blue", powderblue);
		byName.set("purple", purple = Rgb.fromInt(0x800080));
		byName.set("red", red = Rgb.fromInt(0xff0000));
		byName.set("rosybrown", rosybrown = Rgb.fromInt(0xbc8f8f));
		byName.set("rosy brown", rosybrown);
		byName.set("royalblue", royalblue = Rgb.fromInt(0x4169e1));
		byName.set("royal blue", royalblue);
		byName.set("saddlebrown", saddlebrown = Rgb.fromInt(0x8b4513));
		byName.set("saddle brown", saddlebrown);
		byName.set("salmon", salmon = Rgb.fromInt(0xfa8072));
		byName.set("sandybrown", sandybrown = Rgb.fromInt(0xf4a460));
		byName.set("sandy brown", sandybrown);
		byName.set("seagreen", seagreen = Rgb.fromInt(0x2e8b57));
		byName.set("sea green", seagreen);
		byName.set("seashell", seashell = Rgb.fromInt(0xfff5ee));
		byName.set("sea shell", seashell);
		byName.set("sienna", sienna = Rgb.fromInt(0xa0522d));
		byName.set("silver", silver = Rgb.fromInt(0xc0c0c0));
		byName.set("skyblue", skyblue = Rgb.fromInt(0x87ceeb));
		byName.set("sky blue", skyblue);
		byName.set("slateblue", slateblue = Rgb.fromInt(0x6a5acd));
		byName.set("slate blue", slateblue);
		byName.set("slategray", slategray = slategrey = Rgb.fromInt(0x708090));
		byName.set("slate gray", slategray);
		byName.set("slategrey", slategrey);
		byName.set("slate grey", slategrey);
		byName.set("snow", snow = Rgb.fromInt(0xfffafa));
		byName.set("springgreen", springgreen = Rgb.fromInt(0x00ff7f));
		byName.set("spring green", springgreen);
		byName.set("steelblue", steelblue = Rgb.fromInt(0x4682b4));
		byName.set("steel blue", steelblue);
		byName.set("tan", tan = Rgb.fromInt(0xd2b48c));
		byName.set("teal", teal = Rgb.fromInt(0x008080));
		byName.set("thistle", thistle = Rgb.fromInt(0xd8bfd8));
		byName.set("tomato", tomato = Rgb.fromInt(0xff6347));
		byName.set("turquoise", turquoise = Rgb.fromInt(0x40e0d0));
		byName.set("violet", violet = Rgb.fromInt(0xee82ee));
		byName.set("wheat", wheat = Rgb.fromInt(0xf5deb3));
		byName.set("white", white = Rgb.fromInt(0xffffff));
		byName.set("whitesmoke", whitesmoke = Rgb.fromInt(0xf5f5f5));
		byName.set("white smoke", whitesmoke);
		byName.set("yellow", yellow = Rgb.fromInt(0xffff00));
		byName.set("yellowgreen", yellowgreen = Rgb.fromInt(0x9acd32));
		byName.set("yellow green", yellowgreen);
	}
}